# Generated by Django 3.0.4 on 2020-04-19 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlightNo', models.CharField(max_length=10)),
                ('Departure', models.TimeField()),
                ('Arrival', models.TimeField()),
                ('Date', models.DateField()),
                ('From', models.CharField(max_length=25)),
                ('To', models.CharField(max_length=25)),
            ],
        )
    ]
