# Generated by Django 3.0.4 on 2020-04-28 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200419_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flightseat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=20)),
                ('svalue', models.BooleanField(default=False)),
            ],
        ),
        
    ]
