# Generated by Django 3.0.4 on 2020-04-30 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200430_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('FlightNo', models.CharField(max_length=10)),
                ('Departure', models.TimeField()),
                ('Arrival', models.TimeField()),
                ('Date', models.DateField()),
                ('From', models.CharField(max_length=25)),
                ('To', models.CharField(max_length=25)),
                ('Seats', models.IntegerField(null=0)),
                ('Price', models.IntegerField(null=0)),
            ],
        ),
        
    ]
