# Generated by Django 3.0.5 on 2020-06-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200430_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
